services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - /mnt/apps/multiple_photographers_app/studioapp_data/mongodb:/data/db

  backend:
    build:
      context: "https://github.com/valianktni1/studioapp.uk.git#main:backend"
    restart: unless-stopped
    depends_on:
      - mongodb
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - "44"
      - "993"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=studioapp
      - CORS_ORIGINS=*
      - JWT_SECRET=f1cca590a5159bb223548dbd72901a169ff2e023c84f4d7f2458d8b44d76a167
      - SUPER_ADMIN_USERNAME=superadmin
      - SUPER_ADMIN_PASSWORD=Stu!d10App_2026xQ
      - UPLOAD_DIR=/data/userfiles
      - BACKUP_DIR=/backup
      - ROOT_DOMAIN=studioappgallery.uk
      - NGINX_VIDEO_SECRET=dc662f6eee919f8f9a6a1cf12c3a56986b8d26c7bf72a051
      - STRIPE_API_KEY=REPLACE_WITH_YOUR_STRIPE_SECRET_KEY
      - EMERGENT_LLM_KEY=REPLACE_WITH_YOUR_EMERGENT_LLM_KEY
      - PUBLIC_BASE_URL=https://studioappgallery.uk
      - NGINX_VIDEO_BASE_URL=https://video.studioappgallery.uk
      - VAAPI_DEVICE=/dev/dri/renderD128
    volumes:
      - /mnt/photographers_data/studioapp_userdata/uploads:/data/userfiles
      - /mnt/photographers_data/studioapp_userdata/backups:/backup

  nginx-video:
    build:
      context: "https://github.com/valianktni1/studioapp.uk.git#main:nginx"
    restart: unless-stopped
    environment:
      - NGINX_VIDEO_SECRET=dc662f6eee919f8f9a6a1cf12c3a56986b8d26c7bf72a051
    volumes:
      - /mnt/photographers_data/studioapp_userdata/uploads:/uploads:ro

  frontend:
    build:
      context: "https://github.com/valianktni1/studioapp.uk.git#main:frontend"
      args:
        REACT_APP_BACKEND_URL: ""
    restart: unless-stopped
    depends_on:
      - backend
      - nginx-video
    ports:
      - "30038:80"
